  input {
    http {
      port => 5044
      codec => json
    }
  }

  filter {
    if [Level] {
      mutate {
        rename => { "Level" => "log_level" }
      }
    }

    if [Properties][Application] {
      mutate {
        add_field => { "service_name" => "%{[Properties][Application]}" }
      }
      mutate {
        lowercase => ["service_name"]
      }
    }
  }

  output {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "%{[service_name]}-logs-%{+YYYY.MM.dd}"
    }
}